name: RTx-Foundry
version: 0.00_20
abstract: Base classes for the OpenFoundry system
author: Autrijus Tang <autrijus@autrijus.org>
license: gpl
distribution_type: module
requires:
  WWW::Mechanize: 0
  Email::Address: 0
  Email::Valid: 0
  MIME::Base64: 0
  HTML::Mason: 0
  HTML::FromText: 0
  XML::RSS: 0
  XML::Simple: 0
  Project::Gantt: 0
  HTML::CalendarMonthSimple: 0
  DBIx::SearchBuilder: 0
  Template: 0
  Image::Dot: 0
no_index:
  directory:
    - etc
    - html
    - po
    - sbin
    - var
    - inc
generated_by: Module::Install version 0.36
