name: RTx-Foundry
version: 0.00_02
abstract: Base classes for the OpenFoundry system
author: Autrijus Tang (autrijus@autrijus.org)
license: gpl
distribution_type: module
requires:
  RTx::Attribute: 0
  RTx::TabbedUI: 0
  WWW::Mechanize: 0
  Email::Valid: 0
  MIME::Base64: 0
  HTML::Mason: 0
recommends:
  VCP: 0
  SVN::Core: 0
no_index:
  directory:
    - html
    - inc
private:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.27
